### ISSUE TITLE
Add instruction about nodemon

### ISSUE THREAD

**Issue by jasonyueyang** [Microsoft/nodejs-guidelines#12]

**Comment by choopage** [comment]
@jasonyueyang I can lend a hand with this. Something like this? 

**Nodemon:** It will watch the files in the directory in which nodemon was started, and if any files change, nodemon will automatically restart your node application. This is convenient during development process.

Using npm to install nodemon is the recommended way (at time of writing):
`npm install -g nodemon`

Using nodemon after installation
`nodemon [your node app]` so for example running express 4 `nodemon bin/www`

---

@jasonyueyang  We can also do a live-server section since TypeScript is mentioned. What do you think?

**Comment by jasonyueyang** [comment]
Thanks @choopage for your nodemon suggestion. I'll add the section and incorporate your comment.

**Comment by mousetraps** [comment]
@choopage - looks great! my only note is try to keep it less caveated - e.g. run `npm install -g nodemon`

**Comment by choopage** [comment]
@mousetraps Thanks for your feedback. I'll try to keep it minimal. By the way, will you mind explaining in detail what is less caveated? I'm assuming that you mean less formal.

**Comment by mousetraps** [comment]
@choopage Np, we're pretty much saying the same thing in different ways :smiley: - fewer caveats in the name of being more concise, otherwise we detract from the underlying message. In this case, the statement was caveated in two ways:
* recommended way (implying there are other ways, which is true, but unnecessary info for the intended audience)
* at time of writing (implied)

**Comment by choopage** [comment]
Thank you for this writing tip @mousetraps, your explanation is clear. It makes sense. I'm happy to have learned something new today.

**Comment by mousetraps** [comment]
@choopage np :smiley:  feel free to submit a PR with this change!
