### ISSUE TITLE
Decide on a useful structure

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejs-guidelines#4]
For now, let's focus on content, but let's eventually find a way to restructure our content to be more useful.

**Comment by felixrieseberg** [comment]
On that point, I just wanted to create an issue - right now, there seems to be one document, which is covering absolute basics (how to use npm), somewhat burrying real useful information for the node community (compiling native addon modules comes to mind).

How would you feel about breaking this whole thing up into two "Welcome to Node" and a "Windows & Node Development Tips"? It'd make it a lot easier for me to contribute, because I'm currently not sure which of those two things `readme.md` is trying to be :rocket

**Comment by felixrieseberg** [comment]
And since I'm already making wild proposals: If we put the contributing guidelines into a `contributing.md`, GitHub will pick them up and reference them throughout the PR process.

**Comment by tstringer** [comment]
:+1: to @felixrieseberg's comment.  As the documentation grows, it'll become cumbersome to navigate and maintain a single-doc reference.

**Comment by felixrieseberg** [comment]
Let me make a quick PR, breaking those things out.

**Comment by mjbvz** [comment]
Looks like this restructuring has already taken place, at least to some degree. Closing this issue but we should still always consider how to improve the document structure to make things clearer and easier to browse.
