### ISSUE TITLE
Add leveldown to list of recommended packages to Verify everything's working

### ISSUE THREAD

**Issue by vicentedealencar** [Microsoft/nodejs-guidelines#43]
First of all, great job on making node development better on windows.

All the packages presented at  [Verify everything's working](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#verify-everythings-working) are installing fine, but the one a want is not working: `leveldown`

Here is what it looks like

![leveldown](https://cloud.githubusercontent.com/assets/1762868/11510322/5a8ff9d4-984a-11e5-8ba9-5a59ba535288.gif)

I am not sure if my machine is too messed up, or if leveldown hits some edge case.

If it makes sense leveldown should be added to the list

**Comment by mousetraps** [comment]
Unfortunately, I have not been blessed with super-human speed-reading skills - can you please post a copy of the output next time instead of a gif? :wink: In any case, I don't believe the errors you are getting are related to machine configuration. Leveldown should work fine, but you'll need to verify that you're using a compatible version of Node/npm (I successfully installed leveldown@1.4.3 using Node v4.2.3 x64).

Closing this issue, as I don't think there's anything inherently special about leveldown that warrants it being added to the list, and this sort of issue would occur with any module, but happy to reopen if we discover otherwise.

**Comment by vicentedealencar** [comment]
leveldown@1.4.4 is installing ok, sorry about the waste of time
