### ISSUE TITLE
Licensing is unclear?

### ISSUE THREAD

**Issue by Martin-Pitt** [Microsoft/nodejs-guidelines#72]
Microsoft needs to clarify the licensing in regards to `windows-build-tools`, if this is an official path pre-requisite for native addon modules for Node.js

Disclaimer: I am not a laywer.

But the following text via the [License Terms](https://www.visualstudio.com/license-terms/mt644918/) makes the silent installation unclear, which might mean that all developers wishing to use native addons for Node.js may be violating Microsoft's own license via their own guidelines:

> SCOPE OF LICENSE. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you may use the software only as expressly permitted in this agreement. In doing so, you must comply with any technical limitations in the software that only allow you to use it in certain ways. . For more information, see www.microsoft.com/licensing. You may not
work around any technical limitations in the software;
reverse engineer, decompile or disassemble the software, or attempt to do so, except and only to the extent required by third party licensing terms governing use of certain open source components that may be included with the software;
**remove, minimize, block or modify any notices of Microsoft or its suppliers;**
use the software in any way that is against the law; or
share, publish, rent or lease the software, or provide the software as a stand-alone hosted as solution for others to use.

Specifically around removing/minimizing/blocking the installer notices, etc.?

**Comment by mjbvz** [comment]
I believe this is out of scope of this repository. Please try following up with the owners windows-build-tools (sorry but I'm not sure who this is)

**Comment by Ristaaf** [comment]
Additionally Microsoft should clarify the licensing terms for Build Tools. 

From what I can understand it is not free to use for everyone, it actually requires a license of Visual Studio. This means that since VS Community edition is free for anyone not in an enterprise company, build tools requires a Visual Studio license if your company is considered an enterprise company (more than 250 employees or more than $1 million in revenue).

It is not really feasible for enterprise companies to pay for a VS license for each employee that will do an npm install with a dependency that requires gyp rebuilds! So if Microsoft is serious about supporting Node on windows, this problem needs to be addressed (and I would actually expect there to be a note on it in the nodejs-guidelines from Microsoft!
